# Site settings
title: Arkans Floating Island
email: arkan@drakon.io
description: > # this means to ignore newlines until "baseurl:"
  The blog of Arkan - programmer, Forge modder and all-round technically-minded idiot.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://drakon.io" # the base hostname & protocol for your site
twitter_username: arkember
github_username:  Emberwalker

# Build settings
markdown: kramdown
timezone: Europe/London
